name: streaming_crud
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.4.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
